### ISSUE TITLE
quic mqtt disconnect fail

### ISSUE THREAD

**Issue by gavinshao111** [emqx/NanoSDK#123]
Is your feature request related to a problem? Please describe.
I set keepalive=30s, and connected to mq broker over quic,
Q1. Call nng_mqtt_disconnect() or nng_close(), but online status is still **online** in emqx dashboard, after 20s, turn to offline, and disconnect callback called.
Q2. I didn't set auto reconnect, but the client will auto reconnect when disconnected.

Describe the solution you'd like
1. After call nng_mqtt_disconnect() or nng_close(), please disconnect immediately.
2. Do not auto reconnect when disconnected.
Thanks

Describe alternatives you've considered
.

Additional context
.

**Comment by JaylinYu** [comment]
1. By simply close the socket, other side have to wait session expired, which means Client SDK has no control over the session status on broker side. But client could send a disconnect to broker and wait for broker to shut down the connection.
2. Understood, will support this soon

**Comment by gavinshao111** [comment]
> 1. By simply close the socket, other side have to wait session expired, which means Client SDK has no control over the session status on broker side. But client could send a disconnect to broker and wait for broker to shut down the connection.
> 2. Understood, will support this soon

how to send a disconnect to broker, not nng_mqtt_disconnect()?

**Comment by gavinshao111** [comment]
release version 0.10.1 has fixed
