### ISSUE TITLE
NanoSDK's QUIC  is not compatible with Nginx QUIC Proxy？

### ISSUE THREAD

**Issue by Merkwan** [emqx/NanoSDK#244]
**Is your feature request related to a problem? Please describe.**
I find NanoSDK's QUIC  is not compatible with Nginx QUIC proxy and SSL handshake failed.In product environment,EMQX server need multiple instances to deploy,so do you consider supporting Nginx QUIC?

**Comment by JaylinYu** [comment]
No, I dont think SDK shall be blamed for handshake fail. MSQUIC handling tls by it self,.
